import type { BlogPost } from './blog';

export const zincPosts: BlogPost[] = [
  {
    slug: 'zinc-galvanising-demand-infrastructure-investment-steel-connection',
    title: 'Zinc Galvanising Demand: Infrastructure Investment and the Steel Connection',
    date: '2022-10-05',
    category: 'zinc',
    excerpt:
      'Infrastructure spending programmes across the US and EU are set to underpin zinc demand for years to come. We examine the galvanising link between steel production and zinc consumption.',
    author: 'SH Metal Commodities',
    paragraphs: [
      'Zinc remains one of the most fundamentally demand-driven metals in the non-ferrous complex. Unlike copper or aluminium, where end-use diversification has broadened over the decades, zinc\'s consumption profile is dominated by a single application: galvanising. Approximately 60 per cent of global refined zinc demand is directed towards the hot-dip galvanising of steel, a process that coats structural and flat steel products with a protective zinc layer to prevent corrosion. This tight linkage to the steel industry means that understanding zinc demand requires, first and foremost, understanding what is happening in steel production and the downstream sectors that consume it.',

      'In recent years, the outlook for galvanised steel demand has been bolstered by a wave of large-scale infrastructure investment programmes. In the United States, the Infrastructure Investment and Jobs Act has earmarked substantial funding for roads, bridges, water systems, and broadband networks — all of which rely heavily on galvanised steel components. In Europe, the recovery and resilience funds deployed after the pandemic have similarly prioritised infrastructure modernisation, including rail networks, energy grids, and public buildings. These programmes are multi-year in nature, meaning their impact on steel and zinc demand is not a short-lived spike but a sustained tailwind that will play out over the better part of a decade.',

      'The relationship between infrastructure spending and zinc consumption is not always immediate or linear. Lead times for major construction projects can stretch over several years, and steel procurement typically occurs well in advance of the physical construction phase. Furthermore, the galvanising intensity of steel varies by application: transmission towers and highway guardrails, for instance, require heavier zinc coatings than standard structural beams. As infrastructure programmes move from planning to execution, the composition of steel orders — and the corresponding zinc content — will become an increasingly important variable for market participants to monitor.',

      'From a specifications standpoint, the galvanising industry predominantly consumes Special High Grade (SHG) zinc, which carries a minimum purity of 99.995 per cent. SHG zinc is the benchmark grade traded on the London Metal Exchange and is the standard feedstock for continuous galvanising lines operated by major steel producers. Lower-grade zinc, such as High Grade (99.99 per cent) or Prime Western (98.5 per cent), is used in some batch galvanising applications and zinc alloy production, but SHG remains the dominant grade by volume. Physical premiums for SHG zinc — the cost above the LME price paid by consumers to secure delivered metal — are a critical barometer of regional supply-demand tightness and logistics conditions.',

      'China\'s role in the zinc-steel equation cannot be overlooked. As the world\'s largest producer and consumer of both steel and zinc, Chinese output decisions have an outsized influence on global balances. In recent years, Chinese steel production has plateaued amid government-directed capacity rationalisation and a troubled property sector. However, infrastructure-led stimulus measures have partially offset the weakness in real estate, supporting galvanised steel demand domestically. On the supply side, Chinese zinc smelters have expanded capacity, but their output has been constrained at times by power shortages, environmental inspections, and fluctuating concentrate availability.',

      'For physical traders, the galvanising demand channel presents both opportunities and complexities. Procurement cycles for large steel mills are typically structured around annual or semi-annual supply contracts, with spot purchases filling gaps during periods of unexpected demand or supply disruption. Regional premiums can diverge significantly depending on warehouse stock levels, freight costs, and local smelter availability. In Europe, for example, premiums have been volatile in recent years due to energy-driven smelter curtailments, which reduced domestic refined zinc output and forced consumers to source metal from further afield.',

      'Looking ahead, the structural case for zinc demand via galvanising remains constructive. The global push to upgrade ageing infrastructure, combined with the steel-intensive nature of renewable energy installations such as wind turbine foundations and solar mounting structures, provides a supportive backdrop for zinc consumption. However, market participants should remain attentive to the cyclical risks inherent in the construction sector, including rising interest rates, labour shortages, and potential delays in government spending disbursements. The zinc market, as ever, will be shaped by the interplay between these macro forces and the microeconomics of smelter production and physical supply chains.',
    ],
  },
  {
    slug: 'shg-zinc-supply-smelter-economics-concentrate-availability',
    title: 'SHG Zinc Supply: Smelter Economics and Concentrate Availability',
    date: '2023-06-14',
    category: 'zinc',
    excerpt:
      'Zinc smelter treatment charges and concentrate supply dynamics are reshaping the refined zinc market. We analyse the key factors driving smelter economics and their impact on metal availability.',
    author: 'SH Metal Commodities',
    paragraphs: [
      'The supply of refined zinc is fundamentally governed by two stages of the value chain: mining and smelting. Zinc ore is extracted from the ground as zinc sulphide concentrate, which must then be processed — typically through roasting, leaching, and electrolysis — to produce the refined Special High Grade (SHG) zinc ingots and slabs that end-users require. The economics of this two-stage process are captured in the treatment charge (TC), the fee that miners pay to smelters for converting concentrate into refined metal. Treatment charges are the single most important indicator of the concentrate market\'s supply-demand balance and, by extension, a leading signal for refined zinc availability.',

      'In recent years, the zinc concentrate market has experienced significant volatility. A series of major mine closures and production curtailments — including the wind-down of legacy operations in Australia, Ireland, and North America — has tightened the global concentrate supply pipeline. At the same time, several new mining projects have faced delays due to permitting challenges, capital cost inflation, and pandemic-related disruptions. The net effect has been a structural tightening of concentrate availability, which has pushed benchmark treatment charges to multi-year lows. For smelters, lower TCs mean reduced processing margins, as the revenue earned from converting concentrate into metal diminishes.',

      'Smelter economics are further complicated by energy costs, which represent a substantial portion of total production expenses. Zinc smelting is an energy-intensive process, particularly the electrolytic refining stage, which requires significant quantities of electricity. In Europe, where energy prices surged to extraordinary levels following disruptions to natural gas supply, several zinc smelters announced production curtailments or temporary closures. At peak energy prices, some European smelters were operating at a loss on a cash-cost basis, making continued production economically irrational. While energy prices have since retreated from their highs, the experience has underscored the vulnerability of European zinc smelting capacity to energy market shocks.',

      'China dominates global zinc smelting, accounting for roughly half of the world\'s refined zinc output. Chinese smelters have continued to expand capacity in recent years, drawn by government incentives and expectations of growing domestic demand. However, Chinese smelter utilisation rates have been inconsistent, affected by periodic power rationing, environmental compliance campaigns, and, critically, the availability of domestic and imported concentrate feed. When global concentrate supply tightens, Chinese smelters — as the largest consumers of imported concentrate — are often the first to feel the squeeze, either through reduced throughput or by accepting lower treatment charges to maintain feed supply.',

      'The interplay between concentrate availability and smelter output has direct implications for the refined zinc market. When smelter production is constrained — whether by tight concentrate supply, high energy costs, or operational issues — the flow of refined metal into the physical market diminishes. This can manifest as declining LME warehouse stocks, widening physical premiums, and tighter spot availability in key consuming regions. Conversely, periods of ample concentrate supply and favourable smelter economics tend to produce surplus refined metal, building inventories and compressing premiums.',

      'For market participants engaged in physical zinc trading, monitoring the concentrate-to-metal pipeline is essential. Key indicators include benchmark and spot treatment charges, smelter capacity utilisation data, and import-export flows of both concentrate and refined metal. The annual benchmark TC negotiations between major miners and smelters, which typically conclude in the first quarter of each year, set the tone for the concentrate market and provide a reference point for spot transactions throughout the year. Deviations between the benchmark and prevailing spot TCs can signal emerging tightness or surplus in the concentrate market well before the effects are visible in refined metal balances.',

      'Looking forward, the outlook for zinc concentrate supply is shaped by a relatively thin project pipeline. New mine developments capable of meaningfully adding to global supply are limited in number, and the lead times from discovery to production typically span a decade or more. Meanwhile, existing operations face grade decline, rising strip ratios, and increasing regulatory burdens. Unless treatment charges recover sufficiently to incentivise sustained smelter investment and expansion, the risk of periodic refined zinc supply shortfalls will persist, particularly during periods of strong demand growth. The zinc supply chain, from mine to smelter to end-user, remains a finely balanced system where disruptions at any stage can have cascading effects on availability and pricing.',
    ],
  },
  {
    slug: 'non-ferrous-metals-2024-cross-market-themes',
    title: 'Non-Ferrous Metals in 2024: Cross-Market Themes',
    date: '2024-01-22',
    category: 'markets',
    excerpt:
      'As 2024 begins, copper, aluminium, and zinc markets share a set of common themes — from energy transition demand to supply-side constraints and macroeconomic uncertainty.',
    author: 'SH Metal Commodities',
    paragraphs: [
      'The non-ferrous metals complex enters 2024 against a backdrop of competing forces. On one hand, the structural demand narrative driven by the global energy transition remains firmly intact: electrification, renewable energy build-outs, grid expansion, and electric vehicle adoption all require significantly more copper, aluminium, and zinc than the fossil-fuel economy they are gradually replacing. On the other hand, the cyclical headwinds of elevated interest rates, a strong US dollar, and uneven global growth have weighed on near-term sentiment and physical consumption in several key markets. The tension between these structural tailwinds and cyclical headwinds is the defining dynamic for base metals as the year gets underway.',

      'Copper has arguably the most compelling long-term supply-demand story in the base metals space. Mine supply growth has consistently disappointed relative to forecasts, with major producing regions such as Chile and Peru grappling with water scarcity, community opposition, and regulatory tightening. At the same time, copper demand is being pulled higher by data centre construction, EV charging infrastructure, and the rewiring of power grids to accommodate distributed renewable generation. The result is a market that many analysts expect to move into sustained deficit over the medium term, supporting prices and physical premiums even in the face of short-term demand softness.',

      'Aluminium presents a somewhat different picture, though the supply-side constraints are no less significant. Global aluminium smelting capacity is heavily concentrated in China, which accounts for nearly 60 per cent of world output. Beijing has signalled a cap on domestic smelting capacity at approximately 45 million tonnes, a policy driven by carbon reduction targets and energy security considerations. Outside China, smelter restarts in Europe have been slow and partial, as producers remain cautious about committing to full production given the risk of renewed energy price volatility. The net effect is a global aluminium market where meaningful supply growth is difficult to achieve, lending structural support to prices.',

      'Zinc, the smallest of the three major base metals by market size, is highly sensitive to the health of the global construction and infrastructure sectors. As discussed in our earlier commentary, galvanising demand — which accounts for the majority of zinc consumption — is closely tied to steel production and end-use activity in construction, automotive, and infrastructure. The concentrate market remains tight, with limited new mine supply expected to come online in the near term. Smelter margins, particularly in Europe, have improved from the crisis levels of 2022 but remain under pressure from elevated energy and input costs. Zinc\'s relatively thin inventory buffer means that even modest demand surprises or supply disruptions can produce outsized price moves.',

      'Several macro themes cut across all three markets. The trajectory of US Federal Reserve monetary policy is a dominant consideration: expectations of interest rate cuts in 2024 have supported risk appetite and weakened the dollar, both of which tend to be positive for metals prices. However, the timing and magnitude of rate reductions remain uncertain, and any delay could dampen the nascent recovery in industrial activity. China\'s economic performance is equally critical. While the post-reopening rebound in Chinese consumption has been more muted than many had hoped, targeted stimulus measures — particularly in infrastructure and manufacturing — have provided a floor for metals demand. The durability of this support, and whether it extends to the beleaguered property sector, will be a key variable throughout the year.',

      'Physical premiums across all three metals offer a real-time gauge of regional supply-demand conditions. In copper, premiums in China have firmed as smelters ramp up production to meet growing downstream demand. In aluminium, European premiums have stabilised after a period of significant decline, reflecting a tentative recovery in regional consumption and constrained local supply. In zinc, premiums have been supported by low exchange warehouse stocks and logistical bottlenecks in key delivery regions. Across the complex, the premium environment in early 2024 suggests that physical markets are generally balanced to slightly tight, even as headline LME prices have been range-bound.',

      'For participants in the physical non-ferrous metals trade, 2024 is likely to be a year of navigating between structural optimism and cyclical caution. The long-term demand case for copper, aluminium, and zinc is well supported by the energy transition and infrastructure investment themes. However, the near-term outlook is clouded by macroeconomic uncertainty, geopolitical risk, and the potential for supply-side surprises — both positive and negative. Maintaining flexibility in procurement strategies, staying close to physical market fundamentals, and managing price risk through appropriate hedging structures will be essential disciplines for market participants seeking to capitalise on the opportunities that this environment presents.',
    ],
  },
  {
    slug: 'zinc-alloys-serving-the-die-casting-industry',
    title: 'Zinc Alloys: Serving the Die-Casting Industry',
    date: '2024-08-30',
    category: 'zinc',
    excerpt:
      'Zamak zinc alloys are the backbone of the die-casting industry, serving automotive, electronics, and hardware applications with precision and efficiency.',
    author: 'SH Metal Commodities',
    paragraphs: [
      'While the galvanising sector dominates zinc consumption by volume, the zinc alloy and die-casting industry represents a significant and technically demanding end-use segment with its own distinct supply chain dynamics. Zinc die-casting alloys — most commonly known under the Zamak family of designations — are precision-engineered materials used to produce complex, high-tolerance components at scale. The die-casting process, in which molten zinc alloy is injected under high pressure into reusable steel moulds, enables the rapid production of intricate parts with excellent surface finish, tight dimensional tolerances, and good mechanical properties. It is a manufacturing process ideally suited to high-volume production runs in the automotive, electronics, hardware, and consumer goods sectors.',

      'The Zamak alloy family, developed originally in the 1920s, comprises several grades differentiated by their aluminium, copper, and magnesium content. Zamak 3 (also designated ZP3 or ZnAl4) is the most widely used grade globally, prized for its balance of castability, mechanical strength, and surface finish quality. Zamak 5 (ZP5 or ZnAl4Cu1) offers higher strength and hardness due to its copper addition, making it preferred for applications requiring greater wear resistance. Zamak 2 (ZP2 or ZnAl4Cu3) provides the highest strength and hardness in the family but is less commonly used due to its tendency toward dimensional instability over time. Each grade is specified by international standards, including EN 1774 in Europe and ASTM B240 in North America, which define strict compositional limits and impurity tolerances.',

      'The quality of the zinc feedstock used to produce these alloys is of paramount importance. Die-casting alloys are typically manufactured from SHG zinc (99.995 per cent purity) to ensure that impurity levels — particularly lead, cadmium, tin, and iron — remain well within the tight limits required by the alloy specifications. Even trace levels of certain impurities can cause intergranular corrosion, surface defects, or reduced mechanical properties in the finished castings. This places a premium on reliable sourcing of high-purity zinc from established smelters with consistent quality records, and on rigorous quality control throughout the alloy production and casting process.',

      'The European die-casting industry is a significant consumer of zinc alloys, with production concentrated in Germany, Italy, France, and Spain. These markets serve the continent\'s automotive sector — still the single largest end-use for zinc die-castings — as well as growing applications in electronics housings, door hardware, bathroom fittings, and industrial components. European die-casters typically operate on just-in-time supply models, requiring reliable and timely delivery of zinc alloy ingots to maintain uninterrupted production schedules. Supply chain disruptions — whether from smelter outages, logistics delays, or raw material shortages — can have rapid downstream consequences, making supply security a high priority for procurement teams.',

      'The automotive sector\'s relationship with zinc die-casting is evolving. Traditional applications such as carburettor bodies and fuel system components have diminished as internal combustion engines give way to electric powertrains. However, new applications are emerging: structural brackets, battery housing components, charging connector housings, and various interior trim and mechanism parts are increasingly specified in zinc alloy due to the material\'s combination of strength, electromagnetic shielding capability, and recyclability. The net effect on zinc alloy demand from the automotive transition is a matter of active debate within the industry, but the consensus view is that zinc die-casting will retain a meaningful role, albeit with a shifting mix of applications.',

      'Beyond automotive, the electronics sector has become an increasingly important market for zinc die-castings. Connectors, enclosures, heat sinks, and structural frames for consumer electronics, telecommunications equipment, and industrial automation systems are all produced via zinc die-casting. The trend toward miniaturisation and higher component density in electronic devices plays to zinc alloy\'s strengths: the hot-chamber die-casting process can produce thin-walled parts with complex geometries that would be difficult or uneconomical to achieve with alternative materials such as aluminium or engineering plastics.',

      'For physical metals traders serving the die-casting supply chain, the market dynamics differ in important ways from the galvanising segment. Volumes are smaller but specifications are tighter. Relationships with end-users tend to be more technical, involving detailed discussion of alloy compositions, impurity limits, ingot formats, and delivery schedules. Pricing structures typically reference the LME zinc price plus a conversion premium that reflects alloy production costs, quality assurance, and logistics. The ability to offer consistent quality, reliable delivery, and technical support is a key differentiator in this segment — factors that reward established, knowledgeable suppliers with long-term customer relationships.',
    ],
  },
  {
    slug: 'metals-trading-volatile-world-risk-management-fundamentals',
    title: 'Metals Trading in a Volatile World: Risk Management Fundamentals',
    date: '2025-04-15',
    category: 'markets',
    excerpt:
      'Price volatility is an inherent feature of metals markets. We outline the fundamentals of risk management and hedging that enable physical traders to navigate uncertain conditions.',
    author: 'SH Metal Commodities',
    paragraphs: [
      'Price volatility is not an aberration in non-ferrous metals markets — it is a permanent feature. Copper, aluminium, and zinc prices are influenced by a vast array of factors: macroeconomic data releases, central bank policy decisions, geopolitical events, supply disruptions, demand shifts, currency movements, and speculative positioning, to name only the most prominent. For physical metals traders, who buy and sell actual metal rather than purely financial instruments, this volatility creates both risk and opportunity. The discipline of risk management — specifically, the use of hedging to neutralise unwanted price exposure — is what allows physical trading businesses to focus on what they do best: sourcing, transporting, blending, and delivering metal to consumers, while earning a margin on the physical service provided.',

      'The London Metal Exchange (LME) sits at the centre of the non-ferrous metals risk management framework. The LME offers standardised futures and options contracts for copper, aluminium, zinc, and several other metals, with a unique daily prompt date structure that allows hedges to be tailored to specific delivery periods. When a physical trader purchases metal — whether from a smelter, a warehouse, or another trader — the price risk associated with that inventory can be offset by selling an equivalent quantity of LME futures. Conversely, when a trader commits to sell metal at a future date, the exposure can be hedged by buying LME futures. This process of matching physical positions with opposing futures positions is the foundation of metals hedging.',

      'A critical concept in metals hedging is basis risk: the risk that the price of the physical metal being traded does not move in perfect lockstep with the LME futures contract used to hedge it. Basis risk arises from several sources. Physical premiums — the regional surcharge above the LME price — can fluctuate independently of the underlying LME price, driven by local supply-demand conditions, logistics costs, and tariffs. Quality differentials between the specific brand or grade of metal being traded and the LME deliverable specification can also introduce basis. Additionally, timing mismatches between the physical transaction and the hedging instrument create calendar basis risk. Effective risk management requires not only hedging the LME price component but also understanding and, where possible, managing these basis exposures.',

      'Margin requirements are another essential consideration for any hedged trading operation. LME futures positions require the posting of initial margin — a deposit held by the clearing house as collateral against potential losses — as well as daily variation margin payments that reflect mark-to-market gains and losses on open positions. In periods of high volatility, margin requirements can increase substantially, placing significant demands on a trading company\'s liquidity. The ability to fund margin calls in a timely manner, without being forced to liquidate positions at unfavourable prices, is a key operational capability. Companies that underestimate their margin funding requirements can find themselves in difficulty precisely when markets are most volatile and liquidity is most strained.',

      'For principal traders — those who take ownership of physical metal and carry inventory — the hedging process is tightly integrated with the commercial workflow. Each physical purchase or sale generates a price exposure that is logged, hedged, and monitored on a position-keeping system. The goal is to maintain a flat or near-flat net position at all times, meaning that the total long physical position is offset by an equivalent short futures position, and vice versa. Deviations from a flat book represent speculative exposure, which most physical trading houses seek to minimise. The discipline of maintaining a flat book ensures that the company\'s profitability is driven by its physical margin — the premium earned on sourcing, processing, and delivering metal — rather than by directional bets on price.',

      'Options provide an additional layer of flexibility in the risk management toolkit. While futures lock in a price, options give the holder the right, but not the obligation, to buy or sell at a specified price. This asymmetric payoff makes options particularly useful for managing contingent exposures — for example, hedging a tender bid that may or may not be awarded, or protecting against downside risk on inventory while retaining the ability to benefit from a price rally. The cost of this flexibility is the option premium, which must be weighed against the potential benefit. In practice, many physical traders use a combination of futures and options to construct hedging strategies that balance cost, flexibility, and risk reduction.',

      'Ultimately, risk management in metals trading is not about eliminating all uncertainty — that would be neither possible nor desirable. It is about identifying, measuring, and controlling the risks that a business takes, so that the risks it retains are those it is best placed to manage and from which it can earn a return. For a physical metals trader, the retained risks are those embedded in the commercial activity itself: the ability to source metal reliably, to identify arbitrage opportunities between regions or time periods, to serve customers with consistent quality and service, and to navigate the logistical complexities of moving metal around the world. Sound risk management practices — disciplined hedging, robust position monitoring, adequate liquidity, and a clear risk appetite — are the foundation upon which all of this commercial activity is built.',
    ],
  },
];
